[package]
name = "asset-io"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
project-io = { path = "../project-io" }
quick-xml.workspace = true
rustix.workspace = true
sha2.workspace = true
uuid.workspace = true

[dev-dependencies]
serde_json.workspace = true
sha2.workspace = true
tempfile.workspace = true
