import type { StudioMessageCatalogue } from "./message-schema";

export const enMessages = {
  "locale.controlLabel": () => "Interface language",
  "locale.zh-CN": () => "简体中文",
  "locale.en": () => "English",
  "projectCenter.reopenProject": ({ name }: { readonly name: string }) => `Reopen ${name}`,
  "projectCenter.projectCount": ({ count }: { readonly count: number }) => (
    count === 1 ? "1 project" : `${count} projects`
  ),
  "error.generic": () => "The operation could not be completed. Try again.", "error.projectLocked": () => "This project is open in another window. Close it and try again.", "error.projectNotFound": () => "This project could not be found.", "error.projectAlreadyExists": () => "A project with this name already exists in that location.", "error.invalidProjectName": () => "The project name is invalid.", "error.projectRecovery": () => "Project recovery could not be completed. Confirm it is not open elsewhere and try again.", "error.assetOperation": () => "The asset operation could not be completed. Try again.", "error.exportOperation": () => "Export PNG could not be completed. Try again.", "error.desktopUnavailable": () => "The desktop service is temporarily unavailable. Try again.", "error.webSandboxDisabled": () => "The Demo sandbox is unavailable.", "error.diagnosticReference": ({ logRef }: { readonly logRef: string }) => `Diagnostic reference: ${logRef}`,
  "app.backendConnecting": () => "Connecting to the project backend…", "app.backendUnavailable": () => "The project backend is temporarily unavailable.",
  "projectCenter.eyebrow": () => "AetherTwin", "projectCenter.title": () => "AetherTwin Studio", "projectCenter.desktopSummary": () => "Start with one of two focused spatial profiles and persist real projects locally.", "projectCenter.sandboxSummary": () => "Explore the real project workflow in this browser session with one of two focused spatial profiles.", "projectCenter.desktopBadge": () => "Local Project · Persisted", "projectCenter.sandboxBadge": () => "Demo sandbox · Not persisted", "projectCenter.actionsLabel": () => "Project actions", "projectCenter.showroom": () => "Showroom", "projectCenter.market": () => "Market", "projectCenter.showroomDescription": () => "Create a Showroom project with an initial floor.", "projectCenter.marketDescription": () => "Create a Market project with an initial floor.", "projectCenter.createShowroom": () => "New Showroom", "projectCenter.createMarket": () => "New Market", "projectCenter.openProject": () => "Open Project", "projectCenter.openDesktopDescription": () => "Choose and open an existing local AetherTwin Project.", "projectCenter.openSandboxDescription": () => "Reopen the most recently used Project in this Demo sandbox session.", "projectCenter.openDesktop": () => "Open local Project", "projectCenter.openSandbox": () => "Open Demo sandbox Project", "projectCenter.recent": () => "Recent Projects", "projectCenter.desktopEmpty": () => "No local Projects yet", "projectCenter.sandboxEmpty": () => "No Demo sandbox Projects yet", "projectCenter.desktopEmptyDescription": () => "Local Projects you create or open appear here.", "projectCenter.sandboxEmptyDescription": () => "Projects you create appear here for this Demo sandbox session.", "projectCenter.reopen": () => "Reopen", "projectCenter.recoveryTitle": () => "Confirm Project recovery", "projectCenter.recoveryDescription": () => "Recovery rebuilds the Project from local checkpoints and command history. Continue only if it is not in use elsewhere.", "projectCenter.recover": () => "Recover Project", "projectCenter.confirmRecover": () => "Confirm recovery",
  "profile.showroom": () => "Showroom", "profile.market": () => "Market", "backend.desktop": () => "Desktop", "backend.sandbox": () => "Demo sandbox",
  "dialog.createTitle": () => "New Project", "dialog.createDesktopDescription": () => "Choose a local folder and create a persisted Project.", "dialog.createSandboxDescription": () => "The Project exists only in this Demo sandbox session and is discarded when the page closes.", "dialog.fixedProfile": () => "Fixed Project profile", "dialog.showroomDescription": () => "Create the M0 starting space for a Showroom Project.", "dialog.marketDescription": () => "Create the M0 starting space for a Market Project.", "dialog.projectName": () => "Project name", "dialog.projectLocation": () => "Project location", "dialog.chooseProjectLocation": () => "Choose Project location", "dialog.sandboxLocationValue": () => "Demo sandbox", "dialog.sandboxLocation": () => "The Demo sandbox location is fixed and not persisted.", "dialog.cancel": () => "Cancel", "dialog.create": () => "Create Project", "dialog.openLocationTitle": () => "Choose Project location", "dialog.openProjectTitle": () => "Open local Project",
  "validation.empty": () => "Enter a Project name.", "validation.dotPath": () => "The Project name cannot be a dot path.", "validation.separator": () => "The Project name cannot contain path separators.", "validation.reservedName": () => "The Project name cannot use a Windows reserved device name.", "validation.trailing": () => "The Project name cannot end with a dot or space.", "validation.tooLong": () => "The Project name cannot exceed 80 characters.",
  "webDemo.loading": () => "Loading the local example…", "webDemo.retry": () => "Retry", "webDemo.notice": () => "Local preview · Changes reset on refresh · Export PNG is desktop-only", "webDemo.projectInvalid": () => "The local example Project is invalid and cannot be opened.", "webDemo.assetUnavailable": () => "A local example asset is temporarily unavailable. Try again.", "webDemo.assetInvalid": () => "A local example asset could not be validated and cannot be opened.", "webDemo.initializationFailed": () => "The local example could not be initialized. Try again.",
  "webDemo.displayName": ({ en }: { readonly zh: string; readonly en: string }) => en,
  "projectCenter.showroomKicker": () => "SHOWROOM", "projectCenter.marketKicker": () => "MARKET", "projectCenter.desktopOpenKicker": () => "OPEN PROJECT", "projectCenter.sandboxOpenKicker": () => "SANDBOX", "projectCenter.recentKicker": () => "RECENT",
} satisfies StudioMessageCatalogue;
