export {
  CURRENT_SCHEMA_VERSION,
  DEFAULT_SCENE_ENVIRONMENT,
  createInitialSnapshot,
  createManifest,
  type AssetRecord,
  type AssetMediaType,
  type AssetRecordV2,
  type InitialProjectInput,
  type ProjectManifest,
  type ProjectProfile,
  type ProjectSnapshot,
  type ProjectSnapshotV2,
  type SaveState,
  type SpatialProject,
  type SpatialProjectV2,
} from "./model";
export {
  identityTransform2D,
  type Bounds2,
  type Point2,
  type Size2,
  type Spatial3D,
  type Transform2D,
} from "./geometry";
export {
  GEOMETRY_EPSILON_MM,
  effectiveWallThickness,
  locateOpening,
  validateOpeningGeometry,
  wallMetricSegments,
  type OpeningGeometryIssue,
  type OpeningGeometryIssueCode,
  type OpeningProjection,
  type WallMetricSegment,
} from "./opening-geometry";
export type {
  Boundary,
  DimensionAnchor,
  DimensionAnnotation,
  Fixture,
  FixtureKind,
  Floor,
  PlanLayer,
  PointOfInterest,
  PointOfInterestKind,
  ProjectRecordBase,
  SpaceUnit,
  SpaceUnitKind,
  SpatialEntity,
  SpatialEntityBase,
  Wall,
  Zone,
} from "./spatial-entities";
export type {
  CalibrationEvidence,
  CameraShot,
  GuidedRoute,
  MaterialAssignment,
  MaterialDefinition,
  MediaAsset,
  Opening,
  PlanReference,
  ProductContent,
  RouteEdge,
  RouteNetwork,
  RouteNode,
  SceneEnvironment,
  StorySequence,
  ThemeConfig,
  Vendor,
} from "./content-model";
export {
  ModelValidationError,
  parseManifest,
  parseSnapshotV2,
  parseSnapshotV3,
  type ModelIssueCode,
} from "./validation";
export {
  defaultLayerIdForFloor,
  migrateSnapshot,
  migrateSnapshot as parseSnapshot,
  snapshotMigrationRegistry,
} from "./migrations";
