/*
 * @Description: 
 * @Version: 1.668
 * @Autor: 地虎降天龙
 * @Date: 2024-08-19 20:24:59
 * @LastEditors: 地虎降天龙
 * @LastEditTime: 2025-08-18 15:03:33
 */
export default {
    name: 'digitalCity',
    title: '数字城市',
    intro: '基于城市场景的可视化展示插件',
    version: '0.0.1',
    author: '地虎降天龙',
    website: 'https://gitee.com/hawk86104',
    state: 'active',
    require: ['resourceManager', 'UIdemo'],
    preview: [
        // { "src": "plugins/digitalCity/preview/buildings.mp4", "type": "video", "name": "buildings", "title": "建筑物" },
        { catalog: { type: 'block', category: 'gis' }, src: 'plugins/digitalCity/preview/buildings.webp', type: 'img', name: 'buildings', title: '建筑物' },
        { catalog: { type: 'block', category: 'effects' }, src: 'plugins/digitalCity/preview/radars.webp', type: 'img', name: 'radars', title: '雷达' },
        { catalog: { type: 'block', category: 'effects' }, src: 'plugins/digitalCity/preview/diffuseCircle.webp', type: 'img', name: 'diffuseCircle', title: '扩散圈球' },
        { catalog: { type: 'block', category: 'effects' }, src: 'plugins/digitalCity/preview/depthBufferDiffuse.webp', type: 'img', name: 'depthBufferDiffuse', title: '带深度的半球扩散' },
        { catalog: { type: 'block', category: 'effects' }, src: 'plugins/digitalCity/preview/weather.webp', type: 'img', name: 'weather', title: '天气' },
        {
            catalog: { type: 'block', category: 'environment' },
            src: 'plugins/digitalCity/preview/wetPuddleRain.webp',
            type: 'img',
            name: 'wetPuddleRain',
            title: '雨天地面积水',
            referenceSource: { title: 'Three.js Awesome Graphics Agent Skills', url: 'https://github.com/scottstts/Threejs-Awesome-Graphics-Agent-Skills' },
        },
        { catalog: { type: 'block', category: 'effects' }, src: 'plugins/digitalCity/preview/lightningStorm.webp', type: 'img', name: 'lightningStorm', title: '闪电' },
        { catalog: { type: 'block', category: 'effects' }, src: 'plugins/digitalCity/preview/stylizedTornado.webp', type: 'img', name: 'stylizedTornado', title: '漫画龙卷风' },
        { catalog: { type: 'block', category: 'environment' }, src: 'plugins/digitalCity/preview/clouds2.webp', type: 'img', name: 'clouds2', title: '云彩2☁️' },
        { catalog: { type: 'block', category: 'effects' }, src: 'plugins/digitalCity/preview/smoke.webp', type: 'img', name: 'smoke', title: '烟' },
        {
            catalog: { type: 'block', category: 'effects' },
            src: 'plugins/digitalCity/preview/fireA.webp',
            type: 'img',
            name: 'fireA',
            title: '火A🔥效果',
            referenceSource: { title: 'jaimetorrealba', url: 'https://lab.jaimetorrealba.com/fire_shaders_demos' },
        },
        { catalog: { type: 'block', category: 'effects' }, src: 'plugins/digitalCity/preview/fireB.webp', type: 'img', name: 'fireB', title: '火B🔥效果' },
        { catalog: { type: 'block', category: 'effects' }, src: 'plugins/digitalCity/preview/fireC.webp', type: 'img', name: 'fireC', title: '火C🔥效果' },
        { catalog: { type: 'block', category: 'effects' }, src: 'plugins/digitalCity/preview/fireD.webp', type: 'img', name: 'fireD', title: '火D🔥效果' },
        { catalog: { type: 'block', category: 'effects' }, src: 'plugins/digitalCity/preview/fireE.webp', type: 'img', name: 'fireE', title: '火E🔥效果' },
        { catalog: { type: 'block', category: 'effects' }, src: 'plugins/digitalCity/preview/fireF.webp', type: 'img', name: 'fireF', title: '火F🔥效果' },
        {
            catalog: { type: 'block', category: 'effects' },
            src: 'plugins/digitalCity/preview/volumetricFluidFire.webp',
            type: 'img',
            name: 'volumetricFluidFire',
            title: 'WebGPU体积流体火焰',
            referenceSource: { title: 'Three.js Awesome Graphics Agent Skills', url: 'https://github.com/scottstts/Threejs-Awesome-Graphics-Agent-Skills' },
        },
        { catalog: { type: 'block', category: 'effects' }, src: 'plugins/digitalCity/preview/fireBall.webp', type: 'img', name: 'fireBall', title: '火球🔥效果' },
        { catalog: { type: 'block', category: 'ui' }, src: 'plugins/digitalCity/preview/heatmap.webp', type: 'img', name: 'heatmap', title: '热力图' },
        { catalog: { type: 'block', category: 'ui' }, src: 'plugins/digitalCity/preview/heatmap2.webp', type: 'img', name: 'heatmap2', title: '建筑物-热力图' },
        { catalog: { type: 'block', category: 'environment' }, src: 'plugins/digitalCity/preview/cityRiver.webp', type: 'img', name: 'cityRiver', title: '城市河流' },
        { catalog: { type: 'block', category: 'lighting' }, src: 'plugins/digitalCity/preview/buildingsPassA.webp', type: 'img', name: 'buildingsPassA', title: '建筑物后期A' },
        { catalog: { type: 'block', category: 'effects' }, src: 'plugins/digitalCity/preview/buildingsEffectA.webp', type: 'img', name: 'buildingsEffectA', title: '建筑物效果A' },
        { catalog: { type: 'block', category: 'ui' }, src: 'plugins/digitalCity/preview/buildingsMarkA.webp', type: 'img', name: 'buildingsMarkA', title: '建筑物标记A' },
        { catalog: { type: 'block', category: 'effects' }, src: 'plugins/digitalCity/preview/roadLines.webp', type: 'img', name: 'roadLines', title: '道路飞线' },
        { catalog: { type: 'block', category: 'effects' }, src: 'plugins/digitalCity/preview/flyLines.webp', type: 'img', name: 'flyLines', title: '飞线' },
        { catalog: { type: 'block', category: 'effects' }, src: 'plugins/digitalCity/preview/fence.webp', type: 'img', name: 'fence', title: '围栏' },
        { catalog: { type: 'block', category: 'effects' }, src: 'plugins/digitalCity/preview/fencePlusPage.webp', type: 'img', name: 'fencePlusPage', title: '高级围栏' },
        { catalog: { type: 'block', category: 'effects' }, src: 'plugins/digitalCity/preview/fenceWave.webp', type: 'img', name: 'fenceWave', title: '波浪围栏' },
        { catalog: { type: 'block', category: 'effects' }, src: 'plugins/digitalCity/preview/regionGlow.webp', type: 'img', name: 'regionGlow', title: '区域内发光' },
        { catalog: { type: 'block', category: 'effects' }, src: 'plugins/digitalCity/preview/rectangleGlowPage.webp', type: 'img', name: 'rectangleGlowPage', title: '矩形渐变区域' },
        { catalog: { type: 'block', category: 'ui' }, src: 'plugins/digitalCity/preview/coneAnchorA.webp', type: 'img', name: 'coneAnchorA', title: '浮锚标识A' },
        { catalog: { type: 'block', category: 'ui' }, src: 'plugins/digitalCity/preview/coneAnchorB.webp', type: 'img', name: 'coneAnchorB', title: '浮锚标识B' },
        { catalog: { type: 'block', category: 'effects' }, src: 'plugins/digitalCity/preview/particleFirefly.webp', type: 'img', name: 'particleFirefly', title: '粒子萤火虫' },
        { catalog: { type: 'scene', category: 'city' }, src: 'plugins/digitalCity/preview/city2.webp', type: 'img', name: 'city2', title: '城市新模型' },
    ],
}
